import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import http from 'node:http';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { createOmniForgeServer } from '../server.mjs';

test('local API requires a token and preserves project/task/memory boundaries', async t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'omniforge-lab-api-'));
  const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
  const projectRoot = path.join(root, 'game');
  fs.mkdirSync(projectRoot);
  const app = createOmniForgeServer({ dataDir: path.join(root, 'data'), repoRoot, token: 'test-token' });
  const url = await app.listen();
  const base = new URL(url).origin;
  t.after(async () => {
    await app.close();
    const relative = path.relative(os.tmpdir(), root);
    if (relative.startsWith('omniforge-lab-api-') && !relative.includes(path.sep)) fs.rmSync(root, { recursive: true, force: true });
  });
  assert.equal((await fetch(`${base}/api/state`)).status, 403);
  const initial = await fetch(url);
  assert.equal(initial.status, 200);
  const html = await initial.text();
  const browserScript = html.match(/<script type="module">([\s\S]*?)<\/script>/)?.[1];
  assert.ok(browserScript?.includes("from '/pane-scope.mjs'"));
  const parsed = spawnSync(process.execPath, ['--check', '--input-type=module'], { input: browserScript, encoding: 'utf8' });
  assert.equal(parsed.status, 0, parsed.stderr);
  const cookie = initial.headers.get('set-cookie');
  assert.match(cookie, /^OmniForgeAuth_[a-f0-9]{16}=test-token; HttpOnly; SameSite=Strict; Path=\/$/);
  assert.equal((await fetch(`${base}/api/state`, { headers: { cookie } })).status, 200);
  const paneModule = await fetch(`${base}/pane-scope.mjs`, { headers: { cookie } });
  assert.equal(paneModule.status, 200);
  assert.match(paneModule.headers.get('content-type'), /text\/javascript/);
  assert.match(await paneModule.text(), /export function reconcilePaneSessions/);
  assert.equal((await fetch(`${base}/api/tasks`, { method: 'POST', headers: { cookie, 'content-type': 'application/json' }, body: '{}' })).status, 403);
  const eventsAbort = new AbortController();
  const events = await fetch(`${base}/api/events`, { headers: { cookie, accept: 'text/event-stream' }, signal: eventsAbort.signal });
  assert.equal(events.status, 200);
  eventsAbort.abort();
  const post = async (route, value) => fetch(`${base}${route}`, { method: 'POST', headers: { 'content-type': 'application/json', 'x-omniforge-token': 'test-token' }, body: JSON.stringify(value) });
  const projectResponse = await post('/api/projects', { name: 'Game', root: projectRoot });
  assert.equal(projectResponse.status, 200);
  const project = await projectResponse.json();
  const task = await (await post('/api/tasks', { projectId: project.id, title: 'Test first' })).json();
  const dependent = await (await post('/api/tasks', { projectId: project.id, title: 'Then fix', dependsOn: [task.id] })).json();
  assert.equal((await post(`/api/tasks/${dependent.id}/status`, { status: 'done' })).status, 409);
  assert.equal((await post(`/api/tasks/${task.id}/status`, { status: 'done' })).status, 200);
  assert.equal((await post(`/api/tasks/${dependent.id}/status`, { status: 'done' })).status, 200);
  assert.equal((await post('/api/memory', { scope: 'project', projectId: project.id, source: 'CONTEXT.md', text: 'Test with fixtures' })).status, 200);
  const state = await (await fetch(`${base}/api/state`, { headers: { cookie } })).json();
  assert.equal(state.projects.length, 1);
  assert.equal(state.tasks.length, 2);
  assert.equal(state.tasks[1].status, 'done');
  assert.equal(Object.hasOwn(state, 'notes'), false);
  const selectedMemory = await (await fetch(`${base}/api/memory?projectId=${project.id}`, { headers: { cookie } })).json();
  assert.equal(selectedMemory.notes[0].source, 'CONTEXT.md');
  const otherRoot = path.join(root, 'other');
  fs.mkdirSync(otherRoot);
  const other = await (await post('/api/projects', { name: 'Other', root: otherRoot })).json();
  assert.equal((await post('/api/memory', { scope: 'project', projectId: other.id, source: 'private', text: 'OTHER_PROJECT_SECRET' })).status, 200);
  const firstMemory = await (await fetch(`${base}/api/memory?projectId=${project.id}`, { headers: { cookie } })).json();
  assert.equal(JSON.stringify(firstMemory).includes('OTHER_PROJECT_SECRET'), false);
  const snapshot = await (await fetch(`${base}/api/state`, { headers: { cookie } })).text();
  assert.equal(snapshot.includes('OTHER_PROJECT_SECRET'), false);
  assert.equal((await post('/api/layout', { split: 10 })).status, 400);
  const utf8 = Buffer.from(JSON.stringify({ scope: 'global', source: 'usuário', text: 'decisão de física: café' }), 'utf8');
  const split = utf8.indexOf(Buffer.from('é', 'utf8')) + 1;
  const splitResponse = await new Promise((resolve, reject) => {
    const request = http.request(`${base}/api/memory`, { method: 'POST', headers: { 'content-type': 'application/json', 'x-omniforge-token': 'test-token' } }, response => {
      const parts = [];
      response.on('data', part => parts.push(part));
      response.on('end', () => resolve({ status: response.statusCode, body: JSON.parse(Buffer.concat(parts).toString('utf8')) }));
    });
    request.on('error', reject);
    request.write(utf8.subarray(0, split));
    setTimeout(() => request.end(utf8.subarray(split)), 10);
  });
  assert.equal(splitResponse.status, 200);
  assert.equal(splitResponse.body.text, 'decisão de física: café');
});

test('separate local instances use distinct authentication cookies', async t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'omniforge-lab-cookie-'));
  const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
  const first = createOmniForgeServer({ dataDir: path.join(root, 'first'), repoRoot, token: 'first-token' });
  const second = createOmniForgeServer({ dataDir: path.join(root, 'second'), repoRoot, token: 'second-token' });
  t.after(async () => {
    await first.close();
    await second.close();
    const relative = path.relative(os.tmpdir(), root);
    if (relative.startsWith('omniforge-lab-cookie-') && !relative.includes(path.sep)) fs.rmSync(root, { recursive: true, force: true });
  });
  const firstUrl = await first.listen();
  const secondUrl = await second.listen();
  const firstCookie = (await fetch(firstUrl)).headers.get('set-cookie');
  const secondCookie = (await fetch(secondUrl)).headers.get('set-cookie');
  assert.notEqual(firstCookie.split('=')[0], secondCookie.split('=')[0]);
  const firstBase = new URL(firstUrl).origin;
  const secondBase = new URL(secondUrl).origin;
  assert.equal((await fetch(`${firstBase}/api/state`, { headers: { cookie: firstCookie } })).status, 200);
  assert.equal((await fetch(`${secondBase}/api/state`, { headers: { cookie: firstCookie } })).status, 403);
  assert.equal((await fetch(`${secondBase}/api/state`, { headers: { cookie: secondCookie } })).status, 200);
});
